[auth]
# exact section name
cookie_secret       = "f570ff3e6ad7cf09939a6261e5099c71"
redirect_uri        = "http://localhost:8501/oauth2callback"

[auth.google]
client_id           = "1077642010514-hcfnkir3uvjkf059l61nppjlqdv7gj9r.apps.googleusercontent.com"
client_secret       = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
# Optional lock-down: only allow gmail.com users
# allowed_domains = ["gmail.com"]
